FROM node:14-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app/frontend
# Cache and Install dependencies

COPY package.json ./
#COPY ./FrontendLS/package.lock.json /Frontend
RUN npm install
# Copy app files
COPY . .
# Expose port
#EXPOSE 3000
# Start the app
CMD [ "npm", "run", "start" ]