version: '3.1'

services:
  app-ms-prod:
    build:
      dockerfile: Dockerfile.prod
      context: .
    image: image-app-ms-prod
    container_name: app-ctn-prod
    ports:
    - "9500:8000"
    environment:
      - PORT=8000
      - MONGO_HOST=mongo-app-ms-prod
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=12345
    depends_on:
      - mongo-app-ms-prod
    restart: always
    networks:
      - net-app-prod

  mongo-app-ms-prod:
    image: mongo:3.6
    container_name: mongo-app-ctn-prod
    ports:
      - "27017:27017"
    volumes:
      - mongo-app-volume-prod:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    networks:
      - net-app-prod

volumes:
  mongo-app-volume-prod:

networks:
  net-app-prod:
